# Generated by Django 4.2 on 2023-10-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.BooleanField(verbose_name='Parent Category')),
                ('sub_category_1', models.BooleanField(blank=True, null=True, verbose_name='Sub Category 1')),
                ('sub_category_2', models.BooleanField(blank=True, null=True, verbose_name='Sub Category 2')),
            ],
        ),
    ]
