# Generated by Django 4.2 on 2023-10-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.CharField(max_length=50, verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Category 1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Category 2'),
        ),
    ]
